### ISSUE TITLE
Instrument Interface: Arbstudio remains at whatever its last DC value when it was stopped

### ISSUE THREAD

**Issue by maij** [nulinspiratie/SilQ#265]
When the arbstudio is stopped it seems to remain playing whatever its last pulse was (I've observed it outputting a constant DC signal).

This is not generally a problem when not running measurements, but if you then target a pulse sequence that does not use this channel, the channel will continue outputting its last value while running a pulse sequence on the other channels.

I'm not sure what the best solution is for this, perhaps just always queing a zero-waveform for unused channels is the right way to go.

---

**Update**

This problem was even worse than previously thought, the arbstudio would output whatever pulse it was previously applying when triggering started again, even if the run command doesn't select those channels. That means you could have large sinusoids (in my case for adiabatic NMR, or in Rosty's case with microwave Q modulation) being applied when a different pulse sequence is loaded that doesn't use these channels.

**Comment by nulinspiratie** [comment]
Wow really? I've never noticed this before, but it could be pretty bad. 
Next time you notice this, can you run `arbstudio_interface.stop()` and see if it persists?

Queueing a zero-waveform for unused channels could be the solution yeah
